// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Utah.Udot.Atspm.Data;

#nullable disable

namespace Utah.Udot.ATSPM.SqlDatabaseProvider.Migrations.Identity
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20260520185308_5_3")]
    partial class _5_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new IdentityContextModelSnapshotAccessor().Build(modelBuilder);
        }

        private sealed class IdentityContextModelSnapshotAccessor : IdentityContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
