// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Utah.Udot.Atspm.Data;

#nullable disable

namespace Utah.Udot.ATSPM.SqlDatabaseProvider.Migrations.Aggregation
{
    [DbContext(typeof(AggregationContext))]
    [Migration("20260507203906_5_3")]
    partial class _5_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new AggregationContextModelSnapshotAccessor().Build(modelBuilder);
        }

        private sealed class AggregationContextModelSnapshotAccessor : AggregationContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
