// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Utah.Udot.Atspm.Data;

#nullable disable

namespace Utah.Udot.ATSPM.SqlLiteDatabaseProvider.Migrations
{
    [DbContext(typeof(ConfigContext))]
    [Migration("20260521170756_5_3")]
    partial class _5_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new ConfigContextModelSnapshotAccessor().Build(modelBuilder);
        }

        private sealed class ConfigContextModelSnapshotAccessor : ConfigContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
